language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix --dry-run
  - vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
